name: FeLib
main: me.felnstaren.felib.FeLib
version: 1.0.0a
author: Felnstaren
description: Library for a lot of my plugins
api-version: 1.16

commands:
 dtest:
  aliases: []
  description: development test command
 dparticle:
  aliases: [dparti]
  description: custom particle command
 prompt:
  aliases: []
  description: core prompt response command
